import Head from "next/head";
import styles from "../styles/Home.module.scss";
import Navbar from "../components/Navbar/Navbar";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Teste-Prático</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Navbar />
    </div>
  );
}
