import Head from "next/head";
import styles from "../styles/Home.module.scss";
import Navbar from "../components/Navbar/Navbar";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Teste-Prático</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Navbar />
      <div className={styles.principalImageContainer}>
        <div className={styles.principalImage} />
      </div>
      <main className={styles.main}>
        <div className={styles.tagContainer}>
          <ul>
            <Link href="#">
              <li>Lorem ipsum</li>
            </Link>
            <Link href="#">
              <li>Lorem ipsum</li>
            </Link>
            <Link href="#">
              <li>Lorem ipsum</li>
            </Link>
          </ul>
        </div>
        <section className={styles.section}>
          <div className={styles.sectionContainer}>
            <h1>
              Lorem ipsum dolor sit amet consectetur adipiscing elit nunc
              rhoncus aliquam arcu
            </h1>

            <div className={styles.text}>
              <h2>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</h2>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc
                rhoncus aliquam arcu. Mauris molestie vestibulum massa, congue
                ultrices sem imperdiet dignissim. Etiam tristique arcu magna.
                Fusce euismod mattis diam, at ultrices ex varius vitae. Ut
                maximus libero nec tincidunt pulvinar. Etiam a auctor dui. Sed
                vehicula eros eu elit elementum ultricies. In egestas lacus
                dolor, in faucibus arcu scelerisque quis. Aliquam urna dolor,
                eleifend at dapibus ac, dapibus at odio. Ut condimentum
                pellentesque lacinia. Mauris tincidunt, mi id venenatis
                porttitor, nibh ipsum laoreet neque, sit
              </p>
            </div>

            <div className={styles.text}>
              <h2>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</h2>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc
                rhoncus aliquam arcu. Mauris molestie vestibulum massa, congue
                ultrices sem imperdiet dignissim. Etiam tristique arcu magna.
                Fusce euismod mattis diam, at ultrices ex varius vitae. Ut
                maximus libero nec tincidunt pulvinar. Etiam a auctor dui. Sed
                vehicula eros eu elit elementum ultricies. In egestas lacus
                dolor, in faucibus arcu scelerisque quis. Aliquam urna dolor,
                eleifend at dapibus ac, dapibus at odio. Ut condimentum
                pellentesque lacinia. Mauris tincidunt, mi id venenatis
                porttitor, nibh ipsum laoreet neque, sit
              </p>
            </div>

            <div className={styles.text}>
              <h2>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</h2>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc
                rhoncus aliquam arcu. Mauris molestie vestibulum massa, congue
                ultrices sem imperdiet dignissim. Etiam tristique arcu magna.
                Fusce euismod mattis diam, at ultrices ex varius vitae. Ut
                maximus libero nec tincidunt pulvinar. Etiam a auctor dui. Sed
                vehicula eros eu elit elementum ultricies. In egestas lacus
                dolor, in faucibus arcu scelerisque quis. Aliquam urna dolor,
                eleifend at dapibus ac, dapibus at odio. Ut condimentum
                pellentesque lacinia. Mauris tincidunt, mi id venenatis
                porttitor, nibh ipsum laoreet neque, sit
              </p>

              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc
                rhoncus aliquam arcu. Mauris molestie vestibulum massa, congue
                ultrices sem imperdiet dignissim. Etiam tristique arcu magna.
                Fusce euismod mattis diam, at ultrices ex varius vitae. Ut
                maximus libero nec tincidunt pulvinar. Etiam a auctor dui. Sed
                vehicula eros eu elit elementum ultricies. In egestas lacus
                dolor, in faucibus arcu scelerisque quis. Aliquam urna dolor,
                eleifend at dapibus ac, dapibus at odio. Ut condimentum
                pellentesque lacinia. Mauris tincidunt, mi id venenatis
                porttitor, nibh ipsum laoreet neque, sit
              </p>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
